account/urls.py
from django.urls import path
from .views import login_page,register_page

app_name = 'account'
urlpatterns = [
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
]

product/urls.py
from django.urls import path
from .views import Index, OrderSubmit

app_name = 'product'
urlpatterns = [
    path('', Index, name='index'),
    path('order/<int:inventoryid>/', OrderSubmit, name='order'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('product.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from city.models import City
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

# واحد های اندازه گیری محصولات
class Unit(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')
    name = models.CharField(max_length=120, unique=True, verbose_name='واحد اندازه گیری')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'واحد اندازه گیری'
        verbose_name_plural = '1 - واحد های اندازه گیری'

#___________________________________________

# محصولات به همراه موجودی کل آنها
class Product(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')
    name = models.CharField(max_length=120, unique=True, verbose_name='نام محصول')
    price = models.PositiveBigIntegerField(verbose_name='قیمت محصول')
    quantity = models.PositiveIntegerField(verbose_name='تعداد محصول')
    type = models.ForeignKey(Unit, related_name='product_unit',on_delete=models.CASCADE ,verbose_name='واحد اندازه گیری')
    image = models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='تصویر')

    def __str__(self):
        return self.name

    def price_formatted(self):
        return f'{self.price:,}'
    price_formatted.short_description = 'قیمت'

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.image.url))

    admin_photo.short_description = 'تصویر'
    admin_photo.allow_tags = True

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = '2 - محصولات'

#___________________________________________

# تمامی انبار های موجود در شهر ها
class Store(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')
    name = models.CharField(max_length=120, unique=True, verbose_name='نام انبار')
    city = models.ForeignKey(City, related_name='store_city',on_delete=models.CASCADE ,verbose_name='شهر انبار')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'انبار'
        verbose_name_plural = '3 - انبار ها'

#___________________________________________

# موجودی هر انبار
class Inventory(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')
    product = models.ForeignKey(Product, related_name='inventory_product',on_delete=models.CASCADE ,verbose_name='محصول مورد نظر')
    store = models.ForeignKey(Store, related_name='incentory_store', on_delete=models.CASCADE, verbose_name='انبار مورد نظر')
    quantity = models.PositiveIntegerField(verbose_name='موجودی این انبار')

    def __str__(self):
        return f'{self.store} - {self.product}'

    class Meta:
        verbose_name = 'موجودی انبار'
        verbose_name_plural = '4 - موجودی انبار ها'
        #برای اینکه یک انبار به همراه یک محصول دوبار تکرار نشود
        unique_together = [("product", "store")]

# سفارشات
class Order(models.Model):
    STATUS = (
        ('pending', 'در انتظار'),
        ('failed', 'رد شده'),
        ('confirmed', 'تایید شده'),
    )
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ردیف')
    user = models.ForeignKey(User, related_name='order_user',on_delete=models.CASCADE ,verbose_name='کاربر')
    product = models.ForeignKey(Product, related_name='order_product',on_delete=models.CASCADE ,verbose_name='محصول')
    store = models.ForeignKey(Store, related_name='order_store', on_delete=models.CASCADE, verbose_name='انبار')
    quantity = models.PositiveIntegerField(verbose_name='تعداد')
    condition = models.CharField(max_length=20, choices=STATUS, verbose_name='وضعیت سفارش')

    def __str__(self):
        return f'{self.user} - {self.product}'

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = '5 - سفارشات'

product/forms.py
from django import forms
from .models import Product, Inventory, Order

# این فرم برای بررسی این است که موجودی کل محصول از موجودی آن در انبار هم کمتر نشود
class ProductForm(forms.ModelForm):

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        product = self.cleaned_data['name']
        product = Product.objects.filter(name__exact=product).first()
        inventory = list(Inventory.objects.filter(product=product).values_list('quantity'))
        used_inventory = 0
        for i in inventory:
            used_inventory += i[0]
        if quantity < used_inventory:
            raise forms.ValidationError(f'با توجه به موجودی انبار ها موجودی این کالا نمیتواند کمتر از {used_inventory} باشد')
        return quantity

    class Meta:
        model = Product
        exclude = []

#___________________________________________

# این فرم برای این است که موجودی انبار ها از موجودی کل یک محصول بیشتر نشود
class InventoryForm(forms.ModelForm):

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        product = self.cleaned_data['product']
        store = self.cleaned_data['store']
        total_inventory = Product.objects.get(id=product.id).quantity
        inventory = list(Inventory.objects.filter(product=product).exclude(store=store).values_list('quantity'))
        used_inventory = 0
        for i in inventory:
            used_inventory += i[0]
        if total_inventory < used_inventory + quantity:
            msg = f'ظرفیت ثبت شده توسط شما {(used_inventory + quantity) - total_inventory } عدد بیشتر از ظرفیت کل این محصول است '
            raise forms.ValidationError(msg)
        return quantity

    class Meta:
        model = Inventory
        exclude = []

class OrderForm(forms.Form):
    quantity_need = forms.IntegerField(min_value=1,
        widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "مقدار مورد نیاز خود را وارد کنید"}))


class OrderSubmitForm(forms.ModelForm):

    def clean_condition(self):
        condition = self.cleaned_data['condition']
        quantity = self.cleaned_data['quantity']
        product = self.cleaned_data['product']
        store = self.cleaned_data['store']
        inventory = Inventory.objects.get(store=store, product=product)
        product = Product.objects.get(id=inventory.product.id)
        if condition=='failed':
            product.quantity += quantity
            inventory.quantity += quantity
        product.save()
        inventory.save()

        return condition

    class Meta:
        model = Order
        exclude = []

product/views.py
from django.shortcuts import render, redirect
from .models import Product, Inventory, Order
from django.contrib.auth.decorators import login_required
from .forms import OrderForm
from django.contrib import messages

@login_required(login_url='/login')
def Index(request):
    user = request.user
    inventorys = Inventory.objects.filter(store__city=user.profile.city)
    context ={
        'inventorys' : inventorys
    }
    return render(request, 'product/index.html', context)


@login_required(login_url='/login')
def OrderSubmit(request,inventoryid):
    inventory = Inventory.objects.get(id__exact=inventoryid)
    order_form = OrderForm(request.POST or None)
    if request.method == 'POST':
        if order_form.is_valid():
            quantity_need = order_form.cleaned_data.get("quantity_need")
            if quantity_need > inventory.quantity:
                order_form.add_error('quantity_need', 'درخواست شما بیشتر از حد مجاز است')
            else:
                Order.objects.create(user=request.user, product=inventory.product, store=inventory.store,quantity=quantity_need, condition='pending')
                inventory.quantity -= quantity_need
                inventory.save()
                product = Product.objects.get(id=inventory.product.id)
                product.quantity -= quantity_need
                product.save()
                messages.success(request, 'سفارش شما با موفقیت ثبت شد')
                return redirect('/')
    context ={
        "inventory" : inventory,
        "order_form": order_form
    }
    return render(request, 'product/order.html', context)

product/templates/product/index.html
{% extends 'base.html' %}
{% load static %}
{% block context %}
    <div class="main">
    <div class="container">
    {% if not request.user.is_authenticated %}
            <p style="text-align: center;padding-top: 60px">براس ثبت سفارش ابتدا به حساب کاربری خود وارد شوید</p>
            <div class="form-group form-button" style="text-align: center;padding: 50px">
            <a href="{% url 'account:login' %}">
                <input type="submit" name="signin" id="signin" class="form-submit" value="ورود"/>
            </a>
            </div>
        {% else %}
        <table>
          <tr>
            <th>نام محصول</th>
            <th>قیمت هر واحد</th>
            <th>موجودی</th>
            <th>تصویر</th>
            <th>سفارش</th>
          </tr>
        {% for inventory in inventorys %}
          <tr>
            <td>{{ inventory.product.name }}</td>
            <td>{{ inventory.product.price }} تومان </td>
            <td>{{ inventory.quantity }} {{ inventory.product.type.name }}</td>
            <td><img style="width: 75px" src="{{ inventory.product.image.url }}"></td>
            <td><a href="{% url 'product:order' inventory.id %}"><button type="button" value="سفارش">ثبت سفارش</button></a></td>
          </tr>
        {% endfor %}
        </table>
    {% endif %}
    </div>
    </div>

{% endblock %}

product/templates/product/order.html
{% extends 'base.html' %}
{% load static %}
{% block context %}
    <div class="main">
    <div class="container" style="padding-bottom: 50px">

        <img style="width: 250px; padding-left: 10px" src="{{ inventory.product.image.url }}">
        <div style="float: right;padding-right: 15px; text-align: right">
        <h2>{{ inventory.product }}</h2>
        <p>قیمت هر {{ inventory.product.type }} {{ inventory.product.price }} تومان</p>
        <p>موجودی : {{ inventory.quantity }} {{ inventory.product.type }}</p>

        <form method="POST" action="" class="register-form" id="login-form">
            {% csrf_token %}
            {% for error in order_form.quantity_need.errors %}
                <span style="color: #bd4147">{{ error }}</span><br>
            {% endfor %}
            <div class="form-group">
                <label for="your_quantity"><i class="zmdi zmdi-card"></i></label>
                {{ order_form.quantity_need }}
            </div>
            <div class="form-group form-button">
                <input type="submit" name="order_form" id="order_form" class="form-submit" value="نهایی کردن سفارش">
            </div>
        </form>

        </div>

    </div>
    </div>

{% endblock %}